// SARTHI Student Data Service
// Adapts Tech Tomorrow student workflows into the SARTHI IMD Meteorological domain model.

export const initialStudentProfile = {
  id: "std-mohit-raj",
  name: "Mohit Raj",
  email: "student.demo@imd.gov.in",
  role: "IMD Meteorological Trainee",
  division: "Numerical Weather Prediction (NWP) Division",
  avatar: "/images/student-img-1.jpg",
  enrolledCoursesCount: 4,
  hoursLearned: 14.5,
  assignmentsDone: 18,
  overallProgress: 92,
  xpPoints: 850,
  certificatesCount: 3,
  attendanceRate: "94%",
};

export const initialCourses = [
  {
    id: "satellite-meteorology",
    slug: "satellite-meteorology",
    title: "Satellite Meteorology & Remote Sensing",
    category: "Remote Sensing",
    level: "Intermediate",
    thumbnail: "/images/satellite-meteorology-thumb.jpg",
    instructor: {
      name: "Dr. R. K. Sharma",
      title: "Scientist-F, IMD New Delhi",
      avatar: "/images/student-img-1.jpg",
    },
    totalLessons: 48,
    completedLessons: 31,
    progress: 65,
    durationHours: 18,
    status: "active",
    nextLesson: "3. INSAT-3D & 3DR Radiance Analysis",
    description: "Deep dive into geostationary and polar-orbiting meteorological satellites, radiance calibration, and multi-spectral convective cloud tracking.",
    isBookmarked: true,
  },
  {
    id: "nwp-modeling",
    slug: "nwp-modeling",
    title: "Numerical Weather Prediction (NWP) Modeling",
    category: "Modeling",
    level: "Advanced",
    thumbnail: "/images/nwp-modeling-thumb.jpg",
    instructor: {
      name: "Prof. S. N. Mukherjee",
      title: "Director (NWP), Ministry of Earth Sciences",
      avatar: "/images/student-img-2.jpg",
    },
    totalLessons: 36,
    completedLessons: 36,
    progress: 100,
    durationHours: 24,
    status: "completed",
    nextLesson: "All modules completed",
    description: "Comprehensive study of atmospheric primitive equations, grid parameterization, dynamic data assimilation, and WRF ensemble modeling.",
    isBookmarked: true,
  },
  {
    id: "doppler-radar-dynamics",
    slug: "doppler-radar-dynamics",
    title: "Doppler Weather Radar (DWR) & Severe Storm Dynamics",
    category: "Radar Meteorology",
    level: "Intermediate",
    thumbnail: "/images/doppler-radar-thumb.jpg",
    instructor: {
      name: "Dr. Ananya Verma",
      title: "Radar Specialist, IMD Radar Network",
      avatar: "/images/student-img-3.jpg",
    },
    totalLessons: 40,
    completedLessons: 16,
    progress: 40,
    durationHours: 16,
    status: "active",
    nextLesson: "Radial Velocity De-aliasing Algorithms",
    description: "Reflectivity interpretation, dual-polarization signatures, mesocyclone detection, and nowcasting severe convective storms.",
    isBookmarked: false,
  },
  {
    id: "climate-trend-analytics",
    slug: "climate-trend-analytics",
    title: "Monsoon Synoptic Forecasting & Climate Trends",
    category: "Climatology",
    level: "Advanced",
    thumbnail: "/images/monsoon-climate-thumb.jpg",
    instructor: {
      name: "Dr. Sunita Deshmukh",
      title: "Senior Climatologist, IMD Pune",
      avatar: "/images/student-img-2.jpg",
    },
    totalLessons: 32,
    completedLessons: 0,
    progress: 0,
    durationHours: 20,
    status: "not-started",
    nextLesson: "Module 1: Indian Ocean Dipole (IOD) & ENSO Teleconnections",
    description: "Diagnostic analysis of the South Asian Summer Monsoon, intraseasonal oscillations (MJO), and statistical climate downscaling.",
    isBookmarked: false,
  },
];

export const initialLiveClasses = [
  {
    id: "live-session-1",
    title: "Satellite Imagery Live Analysis & Convective Cell Tracking",
    courseId: "satellite-meteorology",
    courseName: "Satellite Meteorology & Remote Sensing",
    instructor: "Dr. R. K. Sharma",
    instructorTitle: "Scientist-F, IMD",
    instructorAvatar: "/images/student-img-1.jpg",
    date: "2026-03-10",
    day: "10",
    month: "MAR",
    time: "10:00 AM - 11:30 AM IST",
    status: "live", // 'live' | 'upcoming' | 'completed'
    roomUrl: "/dashboard/live?room=sat-analysis-101",
    description: "Live demonstration of real-time INSAT-3DR thermal infrared channel calibration and identifying rapid convective cloud growth.",
    attendeesCount: 42,
    isToday: true,
  },
  {
    id: "live-session-2",
    title: "Doppler Radar Velocity Profiles & Supercell Signature Workshop",
    courseId: "doppler-radar-dynamics",
    courseName: "Doppler Weather Radar (DWR)",
    instructor: "Dr. Ananya Verma",
    instructorTitle: "Radar Specialist, IMD",
    instructorAvatar: "/images/student-img-3.jpg",
    date: "2026-03-12",
    day: "12",
    month: "MAR",
    time: "02:00 PM - 03:30 PM IST",
    status: "upcoming",
    roomUrl: "/dashboard/live?room=radar-workshop-102",
    description: "Hands-on analysis of radial velocity scans from Kolkata and Chennai S-Band Doppler radars during pre-monsoon squall events.",
    attendeesCount: 38,
    isToday: false,
  },
  {
    id: "live-session-3",
    title: "Monsoon Synoptic Dynamics & WRF Model Initialization",
    courseId: "nwp-modeling",
    courseName: "Numerical Weather Prediction",
    instructor: "Prof. S. N. Mukherjee",
    instructorTitle: "Director (NWP), MoES",
    instructorAvatar: "/images/student-img-2.jpg",
    date: "2026-03-15",
    day: "15",
    month: "MAR",
    time: "04:00 PM - 05:30 PM IST",
    status: "upcoming",
    roomUrl: "/dashboard/live?room=nwp-seminar-103",
    description: "Interactive session on setting domain nesting boundaries and parameterizing cumulus convection in high-resolution WRF models.",
    attendeesCount: 56,
    isToday: false,
  },
  {
    id: "live-session-4",
    title: "Atmospheric Sounding & Skew-T Log-P Diagnostic Clinic",
    courseId: "satellite-meteorology",
    courseName: "Atmospheric Thermodynamics",
    instructor: "Dr. R. K. Sharma",
    instructorTitle: "Scientist-F, IMD",
    instructorAvatar: "/images/student-img-1.jpg",
    date: "2026-03-05",
    day: "05",
    month: "MAR",
    time: "11:00 AM - 12:30 PM IST",
    status: "completed",
    recordingUrl: "#",
    description: "Review of Cape, Cin, LCL, and Lifted Index computations from GPS Radiosonde soundings.",
    attendeesCount: 49,
    isToday: false,
  },
];

export const initialAssignments = [
  {
    id: "asn-1",
    title: "INSAT-3D & 3DR Radiance Analysis & Cloud Masking",
    courseId: "satellite-meteorology",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    dueDate: "2026-03-12T23:59:59Z",
    dueDateFormatted: "Mar 12, 2026",
    maxScore: 100,
    passingScore: 70,
    status: "pending", // 'pending' | 'submitted' | 'graded' | 'overdue'
    score: null,
    submittedAt: null,
    submissionNotes: null,
    submissionFiles: [],
    instructor: {
      name: "Dr. R. K. Sharma",
      email: "rk.sharma@imd.gov.in",
      avatar: "/images/student-img-1.jpg",
    },
    description: `### Mission Objective
Extract brightness temperature values from the thermal infrared channels (TIR1: 10.8 µm and TIR2: 12.0 µm) of INSAT-3DR over the Bay of Bengal region during a developing cyclonic depression.

### Submission Instructions
1. Download the sample HDF5/NetCDF dataset provided in the lesson repository.
2. Implement split-window brightness temperature difference (BTD = T11 - T12) calculation to isolate thin cirrus from deep convective cores.
3. Generate a plotted contour map showing minimum cloud top brightness temperatures.
4. Export your code script (.py or .ipynb) and final summary report (.pdf).`,
  },
  {
    id: "asn-2",
    title: "Doppler Radar Radial Velocity Calibration & De-Aliasing",
    courseId: "doppler-radar-dynamics",
    courseTitle: "Doppler Weather Radar (DWR)",
    dueDate: "2026-03-18T23:59:59Z",
    dueDateFormatted: "Mar 18, 2026",
    maxScore: 120,
    passingScore: 84,
    status: "pending",
    score: null,
    submittedAt: null,
    submissionNotes: null,
    submissionFiles: [],
    instructor: {
      name: "Dr. Ananya Verma",
      email: "ananya.verma@imd.gov.in",
      avatar: "/images/student-img-3.jpg",
    },
    description: `### Mission Objective
Apply the 2D Bargen-Brown Nyquist velocity unfolding algorithm to a raw Doppler radial velocity scan containing folded Nyquist velocities exceeding 32 m/s.

### Deliverables
- Python script utilizing Py-ART or wradlib.
- Visual comparison plot of raw velocity scan vs de-aliased velocity scan.
- 1-page analytical explanation of shear boundary identification.`,
  },
  {
    id: "asn-3",
    title: "NWP Planetary Boundary Layer (PBL) Parameterization Modeling",
    courseId: "nwp-modeling",
    courseTitle: "Numerical Weather Prediction (NWP) Modeling",
    dueDate: "2026-02-28T23:59:59Z",
    dueDateFormatted: "Feb 28, 2026",
    maxScore: 100,
    passingScore: 70,
    status: "graded",
    score: 95,
    feedback: "Exceptional formulation of the Yonsei University (YSU) PBL scheme. The comparative diurnal boundary layer height analysis over the central Gangetic plains showed rigorous validation with sounding data.",
    submittedAt: "2026-02-27T18:42:10Z",
    submissionNotes: "Implemented both Mellor-Yamada-Janjic and YSU schemes and compared surface heat flux deviations.",
    submissionFiles: ["pbl_comparison_report_mohit_raj.pdf", "namelist.input"],
    instructor: {
      name: "Prof. S. N. Mukherjee",
      email: "sn.mukherjee@imd.gov.in",
      avatar: "/images/student-img-2.jpg",
    },
    description: "Compare turbulent kinetic energy profiles and surface potential temperature between local and non-local PBL parameterization schemes in WRF simulations.",
  },
  {
    id: "asn-4",
    title: "Synoptic Monsoon Flow Field Computation & Vorticity Budget",
    courseId: "satellite-meteorology",
    courseTitle: "Monsoon Synoptic Forecasting",
    dueDate: "2026-02-20T23:59:59Z",
    dueDateFormatted: "Feb 20, 2026",
    maxScore: 100,
    passingScore: 70,
    status: "graded",
    score: 92,
    feedback: "High precision in kinematic horizontal divergence and relative vorticity calculations at 850 hPa and 200 hPa levels.",
    submittedAt: "2026-02-19T21:15:00Z",
    submissionNotes: "Analyzed the monsoon trough positioning and low-level jet intensity over the Arabian Sea.",
    submissionFiles: ["synoptic_vorticity_analysis.pdf"],
    instructor: {
      name: "Dr. Sunita Deshmukh",
      email: "sunita.deshmukh@imd.gov.in",
      avatar: "/images/student-img-2.jpg",
    },
    description: "Calculate geostrophic and ageostrophic wind components from 00 UTC geopotential height fields during active monsoon epochs.",
  },
];

export const initialQuizzes = [
  {
    id: "quiz-sat-diag",
    title: "Satellite Meteorology Diagnostic Assessment",
    courseId: "satellite-meteorology",
    courseName: "Satellite Meteorology & Remote Sensing",
    durationMin: 15,
    questionsCount: 5,
    totalPoints: 100,
    passingScore: 70,
    dueDate: "2026-03-15",
    status: "active", // 'active' | 'completed' | 'overdue'
    attempts: 0,
    bestScore: null,
    questions: [
      {
        id: "q1",
        question: "Which electromagnetic wavelength band is primarily used by meteorological satellites to detect atmospheric water vapor concentration?",
        options: [
          "0.65 µm (Visible Red)",
          "3.9 µm (Shortwave Infrared)",
          "6.7 µm (Water Vapor Absorption Band)",
          "10.8 µm (Thermal Infrared Window)",
        ],
        correctOptionIndex: 2,
        explanation: "The 6.7 µm absorption band of water vapor is optimal for measuring moisture channels in the upper and middle troposphere.",
      },
      {
        id: "q2",
        question: "What is the orbital altitude of India's geostationary meteorological satellite INSAT-3DR above the equator?",
        options: [
          "Approximately 850 km",
          "Approximately 35,786 km",
          "Approximately 20,200 km",
          "Approximately 1,200 km",
        ],
        correctOptionIndex: 1,
        explanation: "Geostationary satellites maintain an altitude of ~35,786 km so their orbital period matches Earth's rotation (24 hours).",
      },
      {
        id: "q3",
        question: "In split-window channel analysis, why is the difference between TIR1 (10.8 µm) and TIR2 (12.0 µm) useful?",
        options: [
          "It measures stratospheric ozone depletion",
          "It corrects for low-level atmospheric water vapor attenuation",
          "It measures cosmic microwave background noise",
          "It determines solar zenith angle reflection",
        ],
        correctOptionIndex: 1,
        explanation: "TIR2 (12 µm) experiences slightly greater water vapor absorption than TIR1 (10.8 µm), allowing differential absorption correction.",
      },
      {
        id: "q4",
        question: "Enhanced convective cloud tops typically appear with what characteristic in color-enhanced infrared imagery?",
        options: [
          "Very high positive brightness temperatures (> 300 K)",
          "Extremely cold brightness temperatures (< -60°C / 213 K)",
          "Zero reflectivity across all visible channels",
          "Uniform gray gradient without texture",
        ],
        correctOptionIndex: 1,
        explanation: "Deep cumulonimbus clouds puncture the tropopause, radiating at extreme cold temperatures often below -60°C to -80°C.",
      },
      {
        id: "q5",
        question: "Which instrument onboard INSAT-3D provides vertical temperature and humidity profiles of the atmosphere?",
        options: [
          "Six-channel Imager",
          "19-channel Sounder",
          "Data Relay Transponder (DRT)",
          "Doppler Velocity Scatterometer",
        ],
        correctOptionIndex: 1,
        explanation: "The 19-channel Sounder (18 infrared and 1 visible) measures radiance across narrow vertical absorption bands to reconstruct atmospheric profiles.",
      },
    ],
  },
  {
    id: "quiz-nwp-mastery",
    title: "NWP Data Assimilation & Modeling Mastery Test",
    courseId: "nwp-modeling",
    courseName: "Numerical Weather Prediction (NWP) Modeling",
    durationMin: 12,
    questionsCount: 4,
    totalPoints: 100,
    passingScore: 70,
    dueDate: "2026-03-20",
    status: "active",
    attempts: 0,
    bestScore: null,
    questions: [
      {
        id: "nq1",
        question: "What is the Courant-Friedrichs-Lewy (CFL) condition primarily used for in numerical fluid modeling?",
        options: [
          "To enforce mass conservation at ocean boundaries",
          "To guarantee computational stability when selecting time step Δt relative to grid spacing Δx",
          "To calibrate satellite radiative transfer models",
          "To adjust soil moisture initialization",
        ],
        correctOptionIndex: 1,
        explanation: "The CFL condition (|u| * Δt / Δx ≤ C_max) ensures that numerical waves do not propagate faster than information can cross grid cells.",
      },
      {
        id: "nq2",
        question: "In 3D-Var and 4D-Var data assimilation, what represents the background error covariance matrix?",
        options: ["B matrix", "R matrix", "H forward operator", "A posterori matrix"],
        correctOptionIndex: 0,
        explanation: "The B matrix encapsulates the spatial and cross-variable correlations of background model forecast errors.",
      },
      {
        id: "nq3",
        question: "Which coordinate system is predominantly adopted in modern non-hydrostatic atmospheric models like WRF?",
        options: [
          "True geometric height z",
          "Standard isobaric pressure p",
          "Terrain-following mass or hybrid-sigma pressure coordinate (η)",
          "Isentropic potential temperature surfaces θ",
        ],
        correctOptionIndex: 2,
        explanation: "Terrain-following coordinates smoothly conform to complex topography near the surface while transitioning to pure pressure aloft.",
      },
      {
        id: "nq4",
        question: "A high convective available potential energy (CAPE) value exceeding 3000 J/kg indicates what atmospheric condition?",
        options: [
          "Absolute thermodynamic stability with zero updraft potential",
          "Extremely high thermodynamic instability favorable for severe convection",
          "Prevalence of dense winter fog and thermal inversions",
          "Complete saturation of the middle troposphere",
        ],
        correctOptionIndex: 1,
        explanation: "CAPE > 3000 J/kg represents tremendous buoyant energy capable of accelerating air parcels into violent thunderstorms.",
      },
    ],
  },
  {
    id: "quiz-radar-completed",
    title: "Doppler Radar Interpretation & Velocity Diagnostics",
    courseId: "doppler-radar-dynamics",
    courseName: "Doppler Weather Radar (DWR)",
    durationMin: 15,
    questionsCount: 5,
    totalPoints: 100,
    passingScore: 70,
    dueDate: "2026-02-15",
    status: "completed",
    attempts: 2,
    bestScore: 92,
    completedAt: "2026-02-14",
    questions: [],
  },
  {
    id: "quiz-thermo-completed",
    title: "Atmospheric Thermodynamics & Skew-T Sounding Mastery",
    courseId: "satellite-meteorology",
    courseName: "Atmospheric Thermodynamics",
    durationMin: 15,
    questionsCount: 5,
    totalPoints: 100,
    passingScore: 70,
    dueDate: "2026-01-30",
    status: "completed",
    attempts: 1,
    bestScore: 88,
    completedAt: "2026-01-29",
    questions: [],
  },
];

export const initialCertificates = [
  {
    id: "SARTHI-IMD-2026-SAT-8821",
    title: "IMD Certified Satellite Meteorological Analyst",
    track: "National Meteorological Training Program",
    authority: "India Meteorological Department (IMD), MoES",
    issueDate: "February 15, 2026",
    score: 94,
    honors: "Gold Distinction (Top 5% Trainees)",
    verificationUrl: "/dashboard/certificates?verify=SARTHI-IMD-2026-SAT-8821",
    qrCodeData: "SARTHI-VERIFIED:MOHIT-RAJ:SAT-METEOROLOGY:2026",
    skills: ["INSAT-3D/3DR Radiance Analysis", "Convective Nowcasting", "Visible & IR Split Window", "Atmospheric Soundings"],
    signatory: "Dr. Mrutyunjay Mohapatra",
    signatoryTitle: "Director General of Meteorology, IMD",
  },
  {
    id: "SARTHI-IMD-2026-NWP-4109",
    title: "Advanced Numerical Weather Prediction (NWP) Specialist",
    track: "Operational High-Performance Modeling",
    authority: "India Meteorological Department (IMD), MoES",
    issueDate: "January 28, 2026",
    score: 96,
    honors: "Platinum Honors (First Class with Distinction)",
    verificationUrl: "/dashboard/certificates?verify=SARTHI-IMD-2026-NWP-4109",
    qrCodeData: "SARTHI-VERIFIED:MOHIT-RAJ:NWP-SPECIALIST:2026",
    skills: ["WRF High-Resolution Modeling", "3D-Var Data Assimilation", "Boundary Layer Parameterization", "HPC Parallel Runs"],
    signatory: "Prof. S. N. Mukherjee",
    signatoryTitle: "Head of NWP Division, IMD",
  },
  {
    id: "SARTHI-IMD-2025-RAD-1920",
    title: "Doppler Radar Meteorology & Storm Diagnostics",
    track: "Severe Weather Nowcasting Certification",
    authority: "India Meteorological Department (IMD), MoES",
    issueDate: "December 20, 2025",
    score: 90,
    honors: "Verified Operational Credential",
    verificationUrl: "/dashboard/certificates?verify=SARTHI-IMD-2025-RAD-1920",
    qrCodeData: "SARTHI-VERIFIED:MOHIT-RAJ:DWR-METEOROLOGY:2025",
    skills: ["Dual-Polarization Interpretation", "Radial Velocity De-Aliasing", "Mesocyclone Detection", "Precipitation Estimation"],
    signatory: "Dr. Ananya Verma",
    signatoryTitle: "Chief Radar Meteorologist, IMD",
  },
];

export const initialConversations = [
  {
    id: "conv-sharma",
    instructorId: "inst-sharma",
    name: "Dr. R. K. Sharma",
    role: "Lead Scientist, Satellite Remote Sensing",
    division: "IMD SatMet Division",
    avatar: "/images/student-img-1.jpg",
    online: true,
    lastActive: "Active now",
    unreadCount: 1,
    messages: [
      {
        id: "msg-1",
        sender: "instructor",
        text: "Hello Mohit! I reviewed your preliminary brightness temperature map for the INSAT-3DR mission.",
        time: "10:15 AM",
        timestamp: "2026-03-06T10:15:00Z",
      },
      {
        id: "msg-2",
        sender: "student",
        text: "Thank you Dr. Sharma! Were the split-window BTD thresholds for the high cirrus masking sufficient?",
        time: "10:20 AM",
        timestamp: "2026-03-06T10:20:00Z",
      },
      {
        id: "msg-3",
        sender: "instructor",
        text: "Yes, exactly. The BTD (10.8 µm - 12.0 µm) > 2.5 K cut off the cirrus plume cleanly. Please submit the final Python script in the Assignment portal.",
        time: "10:24 AM",
        timestamp: "2026-03-06T10:24:00Z",
      },
    ],
  },
  {
    id: "conv-verma",
    instructorId: "inst-verma",
    name: "Dr. Ananya Verma",
    role: "Radar Meteorologist & Doppler Lead",
    division: "IMD Radar Network",
    avatar: "/images/student-img-3.jpg",
    online: false,
    lastActive: "15m ago",
    unreadCount: 0,
    messages: [
      {
        id: "vmsg-1",
        sender: "instructor",
        text: "Don't forget Thursday's practical on radial velocity de-aliasing. Please download the sample volume scan before class.",
        time: "Yesterday",
        timestamp: "2026-03-05T14:30:00Z",
      },
      {
        id: "vmsg-2",
        sender: "student",
        text: "Understood, Dr. Verma. I have initialized Py-ART and loaded the raw sweeps successfully.",
        time: "Yesterday",
        timestamp: "2026-03-05T15:10:00Z",
      },
    ],
  },
  {
    id: "conv-batch2026",
    instructorId: "group-batch2026",
    name: "IMD Trainee Batch 2026",
    role: "Official Trainee Forum",
    division: "Capacity Building Division",
    avatar: "/images/student-img-2.jpg",
    online: true,
    lastActive: "Active now",
    unreadCount: 3,
    isGroup: true,
    messages: [
      {
        id: "bmsg-1",
        sender: "other",
        senderName: "Nisha Chand",
        text: "Has anyone completed the boundary layer parameterization task for NWP?",
        time: "09:05 AM",
        timestamp: "2026-03-06T09:05:00Z",
      },
      {
        id: "bmsg-2",
        sender: "other",
        senderName: "Krish Rishikesh",
        text: "Yes, check the friction velocity u* in your surface output. The YSU scheme produces very realistic daytime depths.",
        time: "09:12 AM",
        timestamp: "2026-03-06T09:12:00Z",
      },
      {
        id: "bmsg-3",
        sender: "student",
        text: "Agreed! Make sure you check both potential temperature and water vapor mixing ratio vertical gradients.",
        time: "09:20 AM",
        timestamp: "2026-03-06T09:20:00Z",
      },
    ],
  },
  {
    id: "conv-support",
    instructorId: "helpdesk-sarthi",
    name: "SARTHI Academic Support Desk",
    role: "IMD Training Coordinator",
    division: "Technical & Help Desk",
    avatar: "/images/sarthi-logo.png",
    online: true,
    lastActive: "24/7 Portal",
    unreadCount: 0,
    messages: [
      {
        id: "smsg-1",
        sender: "instructor",
        text: "Welcome to SARTHI! Your verified trainee profile and IMD server credentials have been synchronized.",
        time: "Mar 1",
        timestamp: "2026-03-01T08:00:00Z",
      },
    ],
  },
];

export const initialSettings = {
  name: "Mohit Raj",
  email: "student.demo@imd.gov.in",
  role: "IMD Meteorological Trainee",
  division: "Numerical Weather Prediction (NWP) Division",
  bio: "Meteorological officer and trainee specializing in operational satellite remote sensing, numerical weather modeling, and Doppler radar analysis.",
  phone: "+91 98765 43210",
  location: "New Delhi, India (IMD Headquarters)",
  timezone: "Asia/Kolkata (IST +5:30)",
  avatar: "/images/student-img-1.jpg",
  notifications: {
    emailAlerts: true,
    liveClassReminders: true,
    assignmentDeadlines: true,
    quizAnnouncements: true,
    chatMessages: true,
  },
  security: {
    twoFactorEnabled: true,
    sessionPersistence: true,
  },
};
