// SARTHI Trainer Data Service
// Domain model for India Meteorological Department (IMD) Faculty, Instructors, and Master Trainers.

export const initialTrainerProfile = {
  id: "trainer-rk-sharma",
  name: "Dr. R. K. Sharma",
  title: "Scientist-F & Chief Instructor",
  division: "Satellite Meteorology & NWP Training Division",
  organization: "India Meteorological Department, HQ New Delhi",
  email: "rk.sharma@imd.gov.in",
  avatar: "/images/student-img-1.jpg",
  totalStudents: 186,
  activeCoursesCount: 4,
  pendingEvaluationsCount: 14,
  averagePassRate: 94.8,
  totalTrainingHours: 48.5,
  upcomingBatchesCount: 3,
  officeHours: "Mon-Thu: 15:00 - 17:00 IST",
  roomLocation: "Room 402, IMD Mausam Bhavan, Lodhi Road, New Delhi",
  bio: "Senior atmospheric scientist with 22+ years of research in geostationary satellite data assimilation, radar nowcasting, and tropical cyclone intensity estimation. Directing national capacity building programs for IMD probationary officers and meteorologists.",
};

export const initialTrainerCourses = [
  {
    id: "satellite-meteorology",
    slug: "satellite-meteorology",
    title: "Satellite Meteorology & Remote Sensing",
    category: "Remote Sensing",
    level: "Intermediate",
    status: "active",
    enrolledCount: 68,
    completionRate: 72,
    totalModules: 6,
    totalLessons: 48,
    durationHours: 18,
    thumbnail: "/images/satellite-meteorology-thumb.jpg",
    lastUpdated: "2026-03-02",
    nextLiveClass: "10 MAR 2026, 10:00 AM",
    description: "Deep dive into geostationary and polar-orbiting meteorological satellites, radiance calibration, and multi-spectral convective cloud tracking.",
    modules: [
      {
        id: "mod-1",
        title: "Module 1: Principles of Satellite Radiometry & Orbit Geometries",
        lessonsCount: 8,
        duration: "3h 15m",
        status: "completed",
        lessons: [
          { id: "les-1", title: "1. Electromagnetic Spectrum & Atmospheric Windows", duration: "25m", type: "video" },
          { id: "les-2", title: "2. Geostationary vs. Low Earth Orbit Mechanics", duration: "30m", type: "video" },
          { id: "les-3", title: "3. INSAT-3D/3DR & Oceansat Payloads Overview", duration: "35m", type: "document" },
        ],
      },
      {
        id: "mod-2",
        title: "Module 2: Multi-Spectral Cloud Classification & RGB Composites",
        lessonsCount: 10,
        duration: "4h 00m",
        status: "active",
        lessons: [
          { id: "les-4", title: "1. Day Microphysics & Night Microphysics RGB", duration: "40m", type: "video" },
          { id: "les-5", title: "2. Water Vapor Channel & Jet Stream Signatures", duration: "35m", type: "video" },
          { id: "les-6", title: "3. Convective Cloud Top Height Estimation (Lab)", duration: "45m", type: "lab" },
        ],
      },
      {
        id: "mod-3",
        title: "Module 3: Quantitative Precipitation Estimation (QPE & HE)",
        lessonsCount: 8,
        duration: "3h 30m",
        status: "upcoming",
        lessons: [
          { id: "les-7", title: "1. Hydro-Estimator & IMSRA Precipitation Algorithm", duration: "30m", type: "video" },
          { id: "les-8", title: "2. NetCDF Radiance Data Processing in Python", duration: "50m", type: "code" },
        ],
      },
    ],
  },
  {
    id: "nwp-modeling",
    slug: "nwp-modeling",
    title: "Numerical Weather Prediction (NWP) Modeling",
    category: "Modeling",
    level: "Advanced",
    status: "active",
    enrolledCount: 52,
    completionRate: 88,
    totalModules: 5,
    totalLessons: 36,
    durationHours: 24,
    thumbnail: "/images/nwp-modeling-thumb.jpg",
    lastUpdated: "2026-02-28",
    nextLiveClass: "12 MAR 2026, 02:00 PM",
    description: "Comprehensive study of atmospheric primitive equations, grid parameterization, dynamic data assimilation, and WRF ensemble modeling.",
    modules: [
      {
        id: "mod-n1",
        title: "Module 1: Atmospheric Primitive Equations & Discretization",
        lessonsCount: 7,
        duration: "4h 30m",
        status: "completed",
        lessons: [
          { id: "les-n1", title: "1. Hydrostatic vs Non-Hydrostatic Formulations", duration: "45m", type: "video" },
          { id: "les-n2", title: "2. Spectral & Grid-Point Finite Difference Schemes", duration: "50m", type: "video" },
        ],
      },
      {
        id: "mod-n2",
        title: "Module 2: Data Assimilation: 3D-Var, 4D-Var & EnKF",
        lessonsCount: 8,
        duration: "5h 00m",
        status: "active",
        lessons: [
          { id: "les-n3", title: "1. Background Error Covariance Matrix (B-Matrix)", duration: "40m", type: "video" },
          { id: "les-n4", title: "2. Radiance Data Assimilation from INSAT-3DR", duration: "55m", type: "lab" },
        ],
      },
    ],
  },
  {
    id: "doppler-radar-dynamics",
    slug: "doppler-radar-dynamics",
    title: "Doppler Weather Radar (DWR) & Severe Storm Dynamics",
    category: "Radar Meteorology",
    level: "Intermediate",
    status: "active",
    enrolledCount: 42,
    completionRate: 64,
    totalModules: 5,
    totalLessons: 40,
    durationHours: 16,
    thumbnail: "/images/doppler-radar-thumb.jpg",
    lastUpdated: "2026-03-01",
    nextLiveClass: "14 MAR 2026, 11:00 AM",
    description: "Reflectivity interpretation, dual-polarization signatures, mesocyclone detection, and nowcasting severe convective storms.",
    modules: [
      {
        id: "mod-r1",
        title: "Module 1: Radar Hardware & Doppler Velocity De-aliasing",
        lessonsCount: 8,
        duration: "3h 40m",
        status: "completed",
        lessons: [
          { id: "les-r1", title: "1. S-Band vs C-Band vs X-Band Applications", duration: "30m", type: "video" },
          { id: "les-r2", title: "2. Nyquist Velocity & Doppler Dilemma Resolution", duration: "45m", type: "lab" },
        ],
      },
    ],
  },
  {
    id: "climate-trend-analytics",
    slug: "climate-trend-analytics",
    title: "Monsoon Synoptic Forecasting & Climate Trends",
    category: "Climatology",
    level: "Advanced",
    status: "draft",
    enrolledCount: 24,
    completionRate: 45,
    totalModules: 4,
    totalLessons: 32,
    durationHours: 20,
    thumbnail: "/images/monsoon-climate-thumb.jpg",
    lastUpdated: "2026-02-25",
    nextLiveClass: "18 MAR 2026, 03:30 PM",
    description: "Diagnostic analysis of the South Asian Summer Monsoon, intraseasonal oscillations (MJO), and statistical climate downscaling.",
    modules: [
      {
        id: "mod-c1",
        title: "Module 1: Large Scale Teleconnections (ENSO & IOD)",
        lessonsCount: 6,
        duration: "3h 10m",
        status: "active",
        lessons: [
          { id: "les-c1", title: "1. Walker Circulation Dynamics & SST Anomalies", duration: "35m", type: "video" },
        ],
      },
    ],
  },
];

export const initialTrainees = [
  {
    id: "std-1",
    name: "Mohit Raj",
    email: "mohit.raj@imd.gov.in",
    division: "NWP Modeling Division",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-1.jpg",
    enrolledCourses: ["satellite-meteorology", "nwp-modeling", "doppler-radar-dynamics"],
    completedCourses: 1,
    attendanceRate: 94,
    quizAvgScore: 92,
    assignmentsSubmitted: 18,
    assignmentsPending: 1,
    performanceTier: "Exemplary",
    status: "active",
    lastActive: "12 mins ago",
    notes: "Top score in NWP Finite Difference formulation. Excellent lab reports.",
  },
  {
    id: "std-2",
    name: "Priya Sharma",
    email: "priya.sharma@imd.gov.in",
    division: "Satellite Meteorology Division",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-2.jpg",
    enrolledCourses: ["satellite-meteorology", "doppler-radar-dynamics"],
    completedCourses: 1,
    attendanceRate: 98,
    quizAvgScore: 96,
    assignmentsSubmitted: 19,
    assignmentsPending: 0,
    performanceTier: "Exemplary",
    status: "active",
    lastActive: "1 hour ago",
    notes: "Outstanding performance on INSAT-3DR Rapid Scan analysis.",
  },
  {
    id: "std-3",
    name: "Rahul Verma",
    email: "rahul.verma@imd.gov.in",
    division: "Radar Operations Division (DWR Pune)",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-3.jpg",
    enrolledCourses: ["doppler-radar-dynamics", "satellite-meteorology"],
    completedCourses: 0,
    attendanceRate: 86,
    quizAvgScore: 84,
    assignmentsSubmitted: 14,
    assignmentsPending: 2,
    performanceTier: "On Track",
    status: "active",
    lastActive: "3 hours ago",
    notes: "Requires revision on Nyquist velocity folding algorithms.",
  },
  {
    id: "std-4",
    name: "Ananya Iyer",
    email: "ananya.iyer@imd.gov.in",
    division: "Agrometeorological Advisory Division",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-2.jpg",
    enrolledCourses: ["satellite-meteorology", "climate-trend-analytics"],
    completedCourses: 1,
    attendanceRate: 91,
    quizAvgScore: 89,
    assignmentsSubmitted: 16,
    assignmentsPending: 1,
    performanceTier: "On Track",
    status: "active",
    lastActive: "5 hours ago",
    notes: "Strong in thermal infrared soil moisture estimation.",
  },
  {
    id: "std-5",
    name: "Vikram Malhotra",
    email: "vikram.m@imd.gov.in",
    division: "Cyclone Warning Division (CWD HQ)",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-1.jpg",
    enrolledCourses: ["satellite-meteorology", "doppler-radar-dynamics", "nwp-modeling"],
    completedCourses: 2,
    attendanceRate: 99,
    quizAvgScore: 98,
    assignmentsSubmitted: 20,
    assignmentsPending: 0,
    performanceTier: "Exemplary",
    status: "active",
    lastActive: "20 mins ago",
    notes: "Consistently delivers immaculate Dvorak T-number estimates.",
  },
  {
    id: "std-6",
    name: "Deepak Choudhury",
    email: "deepak.c@imd.gov.in",
    division: "Aviation Weather Division (IGI Airport)",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-3.jpg",
    enrolledCourses: ["doppler-radar-dynamics"],
    completedCourses: 0,
    attendanceRate: 72,
    quizAvgScore: 68,
    assignmentsSubmitted: 10,
    assignmentsPending: 3,
    performanceTier: "Needs Attention",
    status: "active",
    lastActive: "1 day ago",
    notes: "Missed 2 consecutive live lab sessions due to shift duty.",
  },
  {
    id: "std-7",
    name: "Sneha Mukherjee",
    email: "sneha.m@imd.gov.in",
    division: "Monsoon Forecasting Center (IMD Pune)",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-2.jpg",
    enrolledCourses: ["climate-trend-analytics", "nwp-modeling"],
    completedCourses: 1,
    attendanceRate: 95,
    quizAvgScore: 91,
    assignmentsSubmitted: 17,
    assignmentsPending: 0,
    performanceTier: "On Track",
    status: "active",
    lastActive: "4 hours ago",
    notes: "Excellent work on monsoon low-level jet parameterization.",
  },
  {
    id: "std-8",
    name: "Arjun Nair",
    email: "arjun.nair@imd.gov.in",
    division: "Hydrometeorology Division",
    batch: "IMD Meteorologist Batch 2025-26",
    avatar: "/images/student-img-1.jpg",
    enrolledCourses: ["satellite-meteorology", "doppler-radar-dynamics"],
    completedCourses: 0,
    attendanceRate: 78,
    quizAvgScore: 74,
    assignmentsSubmitted: 11,
    assignmentsPending: 2,
    performanceTier: "Needs Attention",
    status: "active",
    lastActive: "2 days ago",
    notes: "Pending assignment on Doppler QPE calibration curves.",
  },
];

export const initialTrainerAssignments = [
  {
    id: "asg-trainer-1",
    title: "INSAT-3D & 3DR Radiance Calibration and RGB Processing",
    courseId: "satellite-meteorology",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    dueDate: "2026-03-16",
    maxMarks: 100,
    weightage: "15% of Final Grade",
    status: "active",
    totalSubmissions: 46,
    gradedCount: 38,
    pendingCount: 8,
    rubric: [
      { criterion: "Calibration Accuracy (IR & WV Channels)", marks: 35 },
      { criterion: "Cloud Top Temperature Profile Extraction", marks: 35 },
      { criterion: "Code Cleanliness & Python NetCDF Documentation", marks: 30 },
    ],
    description: "Process INSAT-3DR HDF5/NetCDF radiance files, calibrate thermal infrared channels (TIR1 & TIR2), and compute split-window brightness temperature difference for deep convective cell isolation.",
  },
  {
    id: "asg-trainer-2",
    title: "WRF Boundary Layer Parameterization Comparative Study",
    courseId: "nwp-modeling",
    courseTitle: "Numerical Weather Prediction (NWP) Modeling",
    dueDate: "2026-03-20",
    maxMarks: 100,
    weightage: "20% of Final Grade",
    status: "active",
    totalSubmissions: 39,
    gradedCount: 35,
    pendingCount: 4,
    rubric: [
      { criterion: "YSU vs MYJ Boundary Scheme Analysis", marks: 40 },
      { criterion: "Convective Available Potential Energy (CAPE) Sounding", marks: 30 },
      { criterion: "Model Error Metrics (RMSE & Bias)", marks: 30 },
    ],
    description: "Simulate a severe pre-monsoon squall line using the WRF model with Yonsei University (YSU) vs Mellor-Yamada-Janjic (MYJ) PBL schemes. Compare simulated vertical profiles against IMD Radiosonde observations.",
  },
  {
    id: "asg-trainer-3",
    title: "Doppler Velocity De-aliasing & Mesocyclone Detection",
    courseId: "doppler-radar-dynamics",
    courseTitle: "Doppler Weather Radar (DWR) & Severe Storm Dynamics",
    dueDate: "2026-03-24",
    maxMarks: 100,
    weightage: "15% of Final Grade",
    status: "active",
    totalSubmissions: 28,
    gradedCount: 26,
    pendingCount: 2,
    rubric: [
      { criterion: "Velocity Unfolding Algorithm Implementation", marks: 40 },
      { criterion: "Rotational Shear Vector Calculation", marks: 35 },
      { criterion: "TVS (Tornado Vortex Signature) Identification", marks: 25 },
    ],
    description: "Implement a 2D region-growing algorithm to resolve folded Doppler radial velocities exceeding the Nyquist interval (+/- 32 m/s) recorded during the Delhi thunderstorm event.",
  },
];

export const initialSubmissionsQueue = [
  {
    id: "sub-101",
    assignmentId: "asg-trainer-1",
    assignmentTitle: "INSAT-3D & 3DR Radiance Calibration and RGB Processing",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    studentId: "std-1",
    studentName: "Mohit Raj",
    studentEmail: "mohit.raj@imd.gov.in",
    studentAvatar: "/images/student-img-1.jpg",
    division: "NWP Modeling Division",
    submittedAt: "2026-03-05T18:30:00Z",
    status: "pending", // 'pending' | 'graded' | 'revision'
    score: null,
    maxScore: 100,
    files: ["insat3dr_radiance_calibration_mohit.py", "thermal_ir_cloud_mask.png", "calibration_report.pdf"],
    studentNotes: "Computed the split-window difference using Band 3 (10.8 µm) and Band 4 (12.0 µm). Plotted scatter plots against IMD AWS surface thermometers.",
    feedback: "",
    gradedAt: null,
  },
  {
    id: "sub-102",
    assignmentId: "asg-trainer-1",
    assignmentTitle: "INSAT-3D & 3DR Radiance Calibration and RGB Processing",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    studentId: "std-3",
    studentName: "Rahul Verma",
    studentEmail: "rahul.verma@imd.gov.in",
    studentAvatar: "/images/student-img-3.jpg",
    division: "Radar Operations Division",
    submittedAt: "2026-03-05T20:15:00Z",
    status: "pending",
    score: null,
    maxScore: 100,
    files: ["satellite_radiance_script_rahul.py", "rgb_composite_output.nc"],
    studentNotes: "Encountered missing scan lines on Band 2 (3.9 µm), implemented linear spline gap-filling.",
    feedback: "",
    gradedAt: null,
  },
  {
    id: "sub-103",
    assignmentId: "asg-trainer-2",
    assignmentTitle: "WRF Boundary Layer Parameterization Comparative Study",
    courseTitle: "Numerical Weather Prediction (NWP) Modeling",
    studentId: "std-4",
    studentName: "Ananya Iyer",
    studentEmail: "ananya.iyer@imd.gov.in",
    studentAvatar: "/images/student-img-2.jpg",
    division: "Agrometeorological Advisory Division",
    submittedAt: "2026-03-06T09:45:00Z",
    status: "pending",
    score: null,
    maxScore: 100,
    files: ["wrf_ysu_myj_comparison_report.pdf", "wrfout_d03_skewt.png"],
    studentNotes: "Analyzed surface heat fluxes over agricultural plains in Punjab. MYJ scheme produced tighter boundary layer inversion.",
    feedback: "",
    gradedAt: null,
  },
  {
    id: "sub-104",
    assignmentId: "asg-trainer-3",
    assignmentTitle: "Doppler Velocity De-aliasing & Mesocyclone Detection",
    courseTitle: "Doppler Weather Radar (DWR) & Severe Storm Dynamics",
    studentId: "std-6",
    studentName: "Deepak Choudhury",
    studentEmail: "deepak.c@imd.gov.in",
    studentAvatar: "/images/student-img-3.jpg",
    division: "Aviation Weather Division",
    submittedAt: "2026-03-06T14:10:00Z",
    status: "pending",
    score: null,
    maxScore: 100,
    files: ["dwr_delhi_velocity_unfold.py", "shear_vector_field.png"],
    studentNotes: "Implemented 4-point continuity check for de-aliasing.",
    feedback: "",
    gradedAt: null,
  },
  {
    id: "sub-105",
    assignmentId: "asg-trainer-1",
    assignmentTitle: "INSAT-3D & 3DR Radiance Calibration and RGB Processing",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    studentId: "std-2",
    studentName: "Priya Sharma",
    studentEmail: "priya.sharma@imd.gov.in",
    studentAvatar: "/images/student-img-2.jpg",
    division: "Satellite Meteorology Division",
    submittedAt: "2026-03-04T11:20:00Z",
    status: "graded",
    score: 98,
    maxScore: 100,
    files: ["priya_sharma_insat3dr_complete.pdf", "rgb_night_microphysics.tif"],
    studentNotes: "Generated complete Day/Night Microphysics RGB tiles for Cyclone Biparjoy passage.",
    feedback: "Flawless radiance conversion and clear physical interpretation of convective cloud optical depth. Exemplary work!",
    gradedAt: "2026-03-04T16:00:00Z",
  },
  {
    id: "sub-106",
    assignmentId: "asg-trainer-2",
    assignmentTitle: "WRF Boundary Layer Parameterization Comparative Study",
    courseTitle: "Numerical Weather Prediction (NWP) Modeling",
    studentId: "std-5",
    studentName: "Vikram Malhotra",
    studentEmail: "vikram.m@imd.gov.in",
    studentAvatar: "/images/student-img-1.jpg",
    division: "Cyclone Warning Division",
    submittedAt: "2026-03-04T15:45:00Z",
    status: "graded",
    score: 96,
    maxScore: 100,
    files: ["vikram_wrf_pbl_analysis.pdf", "rmse_taylor_diagram.png"],
    studentNotes: "Included Taylor diagrams verifying WRF winds against Chennai radar profiler.",
    feedback: "Thorough statistical verification with Taylor diagrams. Very well formatted report.",
    gradedAt: "2026-03-05T10:30:00Z",
  },
];

export const initialTrainerLiveClasses = [
  {
    id: "live-session-101",
    title: "Satellite Imagery Live Analysis & Convective Cell Tracking",
    courseId: "satellite-meteorology",
    courseName: "Satellite Meteorology & Remote Sensing",
    batch: "All IMD Probationer Batches (Batch 2025-26)",
    date: "2026-03-10",
    day: "10",
    month: "MAR",
    time: "10:00 AM - 11:30 AM IST",
    status: "upcoming", // 'live' | 'upcoming' | 'completed'
    registeredCount: 68,
    attendedCount: 0,
    meetingUrl: "https://meet.imd.gov.in/live-sat-analysis-101",
    passcode: "SAT-IMD-2026",
    agenda: [
      "Real-time INSAT-3DR Rapid Scan imagery review over Bay of Bengal",
      "Over-shooting top detection using 10.8 µm vs 6.7 µm BTD",
      "Live interactive nowcast challenge: Identify pre-convective boundaries",
      "Q&A and student query resolution",
    ],
    materials: ["satellite_live_lecture_slides.pdf", "sample_insat_bay_of_bengal.nc"],
  },
  {
    id: "live-session-102",
    title: "NWP Data Assimilation Masterclass: 3D-Var Matrix Tuning",
    courseId: "nwp-modeling",
    courseName: "Numerical Weather Prediction (NWP) Modeling",
    batch: "NWP & Modeling Specialization Group",
    date: "2026-03-12",
    day: "12",
    month: "MAR",
    time: "02:00 PM - 03:45 PM IST",
    status: "upcoming",
    registeredCount: 52,
    attendedCount: 0,
    meetingUrl: "https://meet.imd.gov.in/live-nwp-masterclass-102",
    passcode: "NWP-IMD-2026",
    agenda: [
      "Background Error (B-Matrix) formulation in WRF-DA",
      "Radiance quality control and cloud-clearing algorithms",
      "Hands-on terminal session: running WRF-DA on HPC cluster",
    ],
    materials: ["wrfda_tutorial_guide.pdf", "b_matrix_sample.dat"],
  },
  {
    id: "live-session-103",
    title: "Doppler Radar Interpretation for Severe Storm Nowcasting",
    courseId: "doppler-radar-dynamics",
    courseName: "Doppler Weather Radar (DWR) & Severe Storm Dynamics",
    batch: "Radar & Nowcasting Officers",
    date: "2026-03-03",
    day: "03",
    month: "MAR",
    time: "11:00 AM - 12:30 PM IST",
    status: "completed",
    registeredCount: 42,
    attendedCount: 40,
    recordingUrl: "https://portal.imd.gov.in/recordings/dwr-nowcast-session3.mp4",
    meetingUrl: "https://meet.imd.gov.in/live-dwr-archive-103",
    agenda: ["Dual-polarization signatures (ZDR, KDP, CC) in hail detection", "Interactive case study: Delhi squall line event"],
    materials: ["dwr_nowcasting_handbook.pdf"],
  },
];

export const initialTrainerQuizzes = [
  {
    id: "quiz-trainer-1",
    title: "Satellite Meteorology Fundamentals & INSAT Payloads",
    courseId: "satellite-meteorology",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    timeLimitMinutes: 20,
    totalQuestions: 5,
    totalAttempts: 58,
    averageScore: 84.5,
    passRate: 91.4,
    status: "published",
    questions: [
      {
        id: "q-1",
        question: "Which INSAT-3DR imager channel is primarily utilized to detect upper-tropospheric water vapor patterns and jet streams?",
        options: ["Visible (0.65 µm)", "Thermal Infrared 1 (10.8 µm)", "Water Vapor (6.7 µm)", "Shortwave Infrared (3.9 µm)"],
        correctOptionIndex: 2,
        explanation: "The 6.7 µm Water Vapor absorption band detects moisture in the 500-300 hPa layer, making upper-level troughs and jet streams easily discernable.",
        difficulty: "Medium",
      },
      {
        id: "q-2",
        question: "In split-window brightness temperature difference (BTD: T11 - T12), negative values over convective clouds usually indicate:",
        options: ["Clear sky over oceans", "Cirrus cloud anvil with small ice crystals", "Desert surface thermal heating", "Low-level fog/stratus"],
        correctOptionIndex: 1,
        explanation: "Differential absorption between 11 µm and 12 µm caused by high-altitude thin cirrus/ice crystals produces negative BTD signatures.",
        difficulty: "Hard",
      },
      {
        id: "q-3",
        question: "The spatial resolution of the INSAT-3DR Visible channel at the sub-satellite point is:",
        options: ["0.5 km", "1.0 km", "4.0 km", "8.0 km"],
        correctOptionIndex: 1,
        explanation: "INSAT-3DR Imager Visible channel has a spatial resolution of 1 km x 1 km at nadir.",
        difficulty: "Easy",
      },
    ],
  },
  {
    id: "quiz-trainer-2",
    title: "Doppler Weather Radar (DWR) Velocity Dynamics",
    courseId: "doppler-radar-dynamics",
    courseTitle: "Doppler Weather Radar (DWR) & Severe Storm Dynamics",
    timeLimitMinutes: 25,
    totalQuestions: 4,
    totalAttempts: 38,
    averageScore: 78.2,
    passRate: 84.2,
    status: "published",
    questions: [
      {
        id: "q-d1",
        question: "If a radar operating at wavelength λ = 10 cm uses a Pulse Repetition Frequency (PRF) of 1000 Hz, what is the unambiguous Nyquist velocity Vmax?",
        options: ["12.5 m/s", "25.0 m/s", "50.0 m/s", "100.0 m/s"],
        correctOptionIndex: 1,
        explanation: "Vmax = (λ * PRF) / 4 = (0.10 * 1000) / 4 = 25.0 m/s.",
        difficulty: "Hard",
      },
    ],
  },
];

export const initialTrainerCertificates = [
  {
    id: "cert-app-1",
    studentId: "std-1",
    studentName: "Mohit Raj",
    studentEmail: "mohit.raj@imd.gov.in",
    courseId: "nwp-modeling",
    courseTitle: "Numerical Weather Prediction (NWP) Modeling",
    division: "NWP Modeling Division",
    completionDate: "2026-03-01",
    finalGrade: "96% (Grade A+)",
    status: "pending_approval", // 'pending_approval' | 'approved' | 'rejected'
    certificateNumber: "SARTHI-2026-NWP-048",
    qrVerificationUrl: "https://sarthi.imd.gov.in/verify/SARTHI-2026-NWP-048",
  },
  {
    id: "cert-app-2",
    studentId: "std-2",
    studentName: "Priya Sharma",
    studentEmail: "priya.sharma@imd.gov.in",
    courseId: "satellite-meteorology",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    division: "Satellite Meteorology Division",
    completionDate: "2026-02-26",
    finalGrade: "98% (Grade A+)",
    status: "pending_approval",
    certificateNumber: "SARTHI-2026-SAT-029",
    qrVerificationUrl: "https://sarthi.imd.gov.in/verify/SARTHI-2026-SAT-029",
  },
  {
    id: "cert-app-3",
    studentId: "std-5",
    studentName: "Vikram Malhotra",
    studentEmail: "vikram.m@imd.gov.in",
    courseId: "satellite-meteorology",
    courseTitle: "Satellite Meteorology & Remote Sensing",
    division: "Cyclone Warning Division",
    completionDate: "2026-02-20",
    finalGrade: "95% (Grade A+)",
    status: "approved",
    approvedAt: "2026-02-22",
    certificateNumber: "SARTHI-2026-SAT-024",
    qrVerificationUrl: "https://sarthi.imd.gov.in/verify/SARTHI-2026-SAT-024",
  },
];

export const initialTrainerConversations = [
  {
    id: "conv-t-1",
    studentId: "std-1",
    studentName: "Mohit Raj",
    studentAvatar: "/images/student-img-1.jpg",
    division: "NWP Division",
    courseContext: "Satellite Meteorology",
    unreadCount: 1,
    isUrgent: true,
    lastMessage: {
      text: "Dr. Sharma, while calibrating the INSAT-3DR TIR1 channel radiance, should we apply the non-linear Planck lookup table or the polynomial calibration coefficients?",
      timestamp: "15 mins ago",
      sender: "student",
    },
    messages: [
      {
        id: "msg-1",
        sender: "student",
        text: "Respected Dr. Sharma, I am working on Assignment 1 for INSAT-3DR radiance calibration.",
        timestamp: "10:30 AM",
      },
      {
        id: "msg-2",
        sender: "trainer",
        text: "Hello Mohit. Great to hear. Let me know if you run into any ambiguities with the HDF5 channel attributes.",
        timestamp: "10:45 AM",
      },
      {
        id: "msg-3",
        sender: "student",
        text: "Dr. Sharma, while calibrating the INSAT-3DR TIR1 channel radiance, should we apply the non-linear Planck lookup table or the polynomial calibration coefficients?",
        timestamp: "11:15 AM",
      },
    ],
  },
  {
    id: "conv-t-2",
    studentId: "std-3",
    studentName: "Rahul Verma",
    studentAvatar: "/images/student-img-3.jpg",
    division: "Radar Division",
    courseContext: "Doppler Radar Dynamics",
    unreadCount: 0,
    isUrgent: false,
    lastMessage: {
      text: "Understood Sir, I will review the Nyquist interval formula and resubmit the de-aliasing code tonight.",
      timestamp: "2 hours ago",
      sender: "student",
    },
    messages: [
      {
        id: "msg-r1",
        sender: "trainer",
        text: "Rahul, please check your velocity folding calculation on ray 142. It is wrapping around at +32 m/s.",
        timestamp: "09:00 AM",
      },
      {
        id: "msg-r2",
        sender: "student",
        text: "Understood Sir, I will review the Nyquist interval formula and resubmit the de-aliasing code tonight.",
        timestamp: "09:30 AM",
      },
    ],
  },
];

export const initialBroadcasts = [
  {
    id: "bcast-1",
    title: "Urgent: Doppler Radar Nowcast Lab Shift Rescheduling",
    targetBatch: "All Trainee Batches",
    sentAt: "2026-03-04 14:00 IST",
    message: "Due to active pre-monsoon squall line tracking over Northern Plains, tomorrow's lab session will analyze live radar feeds from DWR Palam and DWR Safdarjung.",
    recipientCount: 186,
  },
  {
    id: "bcast-2",
    title: "Assignment 1 Submission Deadline Extension",
    targetBatch: "Satellite Meteorology Batch",
    sentAt: "2026-03-01 10:30 IST",
    message: "The deadline for INSAT-3D & 3DR Radiance Calibration report has been extended by 48 hours to accommodate HPC maintenance.",
    recipientCount: 68,
  },
];
